/**
 * 订单模块常量
 */
// 订单列表
export const GETTING_ORDER_LIST = 'GETTING_ORDER_LIST';
export const RECEIVE_ORDER_LIST = 'RECEIVE_ORDER_LIST';


// 订单详情
export const GETTING_ORDER_DETAIL = 'GETTING_ORDER_DETAIL';
export const RECEIVE_ORDER_DETAIL = 'RECEIVE_ORDER_DETAIL';


// 创建订单
export const CREATING_ORDER = 'CREATING_ORDER';
export const RECEIVE_CREATE_ORDER = 'RECEIVE_CREATE_ORDER';


// 更新订单 
export const UPDATING_ORDER = 'UPDATING_ORDER';
export const RECEIVE_UPDATE_ORDER = 'RECEIVE_UPDATE_ORDER';


// 删除订单
export const DELETING_ORDER = 'DELETING_ORDER';
export const RECEIVE_DELETE_ORDER = 'RECEIVE_DELETE_ORDER';
