/**
 * 产品模块常量
 */
// 产品列表
export const GETTING_PRODUCT_LIST = 'GETTING_PRODUCT_LIST';
export const RECEIVE_PRODUCT_LIST = 'RECEIVE_PRODUCT_LIST';


// 产品详情
export const GETTING_PRODUCT_DETAIL = 'GETTING_PRODUCT_DETAIL';
export const RECEIVE_PRODUCT_DETAIL = 'RECEIVE_PRODUCT_DETAIL';


// 创建产品
export const CREATING_PRODUCT = 'CREATING_PRODUCT';
export const RECEIVE_CREATE_PRODUCT = 'RECEIVE_CREATE_PRODUCT';


// 更新产品 
export const UPDATING_PRODUCT = 'UPDATING_PRODUCT';
export const RECEIVE_UPDATE_PRODUCT = 'RECEIVE_UPDATE_PRODUCT';


// 删除产品
export const DELETING_PRODUCT = 'DELETING_PRODUCT';
export const RECEIVE_DELETE_PRODUCT = 'RECEIVE_DELETE_PRODUCT';
