/**
 * 用户模块常量
 */
// 用户列表
export const GETTING_USER_LIST = 'GETTING_USER_LIST';
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST';


// 用户详情
export const GETTING_USER_DETAIL = 'GETTING_USER_DETAIL';
export const RECEIVE_USER_DETAIL = 'RECEIVE_USER_DETAIL';


// 创建用户
export const CREATING_USER = 'CREATING_USER';
export const RECEIVE_CREATE_USER = 'RECEIVE_CREATE_USER';


// 更新用户 
export const UPDATING_USER = 'UPDATING_USER';
export const RECEIVE_UPDATE_USER = 'RECEIVE_UPDATE_USER';


// 删除用户
export const DELETING_USER = 'DELETING_USER';
export const RECEIVE_DELETE_USER = 'RECEIVE_DELETE_USER';
